### ISSUE TITLE
Docker Research Spike

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#12]
Size: 3

Docker is so hot right now.
But do we need to use container technology for this project?

ACs:
- Research using Docker with this project
- Create a branch to run lookingfor in a Docker container
- Demo in a team stand up the pros and cons for using Docker for this application

### Resources:
https://docs.docker.com/compose/rails/
http://www.zdnet.com/article/what-is-docker-and-why-is-it-so-darn-popular/
https://www.ctl.io/developers/blog/post/what-is-docker-and-when-to-use-it/

**Comment by jasonpilz** [comment]
I'd be game for this

**Comment by amcrawford** [comment]
Day 2 Progress:
Have reached out to a couple of mentors who work with Docker in their companies.  Initial thoughts, are that Docker is a really great tool on a large team and project for 1. making uniform setup environments and 2. deploying with lots of external dependencies or syncing deployment of multiple apps but, that for a relatively small project it does add a fair amount of overhead that requires someone to have an intimate understanding of Docker and keep up-to-date on new releases.

So, far, it seems like it might not be a great fit at this stage but, I am going to attempt to get a container up and running this week and document my experiments so that we could revisit it as a group this week or again in the future as the app evolves.

**Comment by rrgayhart** [comment]
Nice work! I think documenting this all in the basecamp would be a good way to wrap up the work when you're ready to do that.

**Comment by amcrawford** [comment]
Added final thoughts to BaseCamp doc. Will leave this issue open for future use unless team would prefer to close for clarity.
