### ISSUE TITLE
[WIP] Reviews of Companies Research

### ISSUE THREAD

**Issue by rrgayhart** [LookingForMe/lookingfor#65]
Either external or internal?
Links to GlassJobs
Other ways to beef up company information

Information on the interview process

**Comment by Salvi6God** [comment]
NOTE:

Although this issue isn't saying to do this, I am currently reading the 'Terms of Use' page to make sure that we will be able to use their API legally. Will update this comment once done to see what I come up with.

**Comment by Salvi6God** [comment]
![glassdoor](http://i.imgur.com/UFSC2Em.png)

**Comment by Salvi6God** [comment]
Glassdoor API off the table

Research a bit more for alternative API's if not then come up with another way that might work for getting the reviews.

**Comment by Salvi6God** [comment]
## Update
I ended up creating a doc on Basecamp that'll provide a brief summary on why Glassdoor's API will not work. Also, I want to point out that I was unsuccessful in finding another alternative in finding out how to get a company's review. I thought using Indeed's API would've helped us in solving this problem but their [API](http://www.indeed.com/jsp/apiinfo.jsp) is not the answer to our problem. 

I'm going to go ahead and close this commit due to not being able to find an alternative in grabbing the reviews for a company.
